### ISSUE TITLE
Random Frezzing

### ISSUE THREAD

**Issue by euphoricrage** [AstroCat2Space/Cadikith-Issues#1]
I'm not sure if this is a problem with the modpack or if it's just on my end, but randomly when playing on multiplayer the whole game just freezes up my FPS doesn't change my memory usage doesn't go up it just stops i can move, but i can't open, attack, or break anything and if it comes back everything starts to happen really fast.

I know you made need the console log, but i couldn't find it.

**Comment by AstroCat2Space** [comment]
It may just be the server if you play with other people, since it doesn't affect your fps and memory usage.

**Comment by euphoricrage** [comment]
it's a LAN connection would it still affect it like that?

**Comment by AstroCat2Space** [comment]
Yes, your local Wi-Fi router performance affects the lan server a lot.

**Comment by AstroCat2Space** [comment]
In other words, this is a problem on your end.
